name: Auto merge

on: pull_request_target

# jobs:
#   auto-approve:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#     if: github.actor == 'dependabot[bot]' || github.actor == 'weblate'
#     steps:
#       - uses: hmarr/auto-approve-action@v3
#       - name: automerge
#         uses: "pascalgn/automerge-action@v0.15.6"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
